name: diagnostic-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.1.3
  - dash=2.5.1
  - dash-auth=1.4.1
  - dash-bootstrap-components=1.2.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - lightgbm=3.3.2
  - numpy=1.23.0
  - pandas=1.4.3
  - pip=22.1.2
  - plotly=5.9.0
  - plotly_express=0.4.1
  - pre-commit=2.19.0
  - pre_commit=2.19.0
  - psycopg2=2.9.3
  - pydantic=1.9.1
  - pytest=7.1.2
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-dotenv=0.20.0
  - pytz=2022.1
  - pyyaml=6.0
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - setuptools=63.1.0
  - sqlalchemy=1.4.39
  - sqlite=3.39.0
  - statsmodels=0.13.2
  - yaml=0.2.5
  - pip:
    - dash-admin-components==0.1.4
