version: 2.1

jobs:
  test:
    parameters:
      conda-environment-name:
        type: string
    docker:
      - image: conda/miniconda3
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          command: |
            conda update -y conda

            if $(conda env list | grep -q "/usr/local/envs/<< parameters.conda-environment-name >>"); then
              echo "Found existing conda env: /usr/local/envs/<< parameters.conda-environment-name >>, skipping creation then"
            else
              conda env create -f environment.yml
            fi

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "environment.yml" }}
          paths:
            - /usr/local/envs/<< parameters.conda-environment-name >>
      - run:
          name: Print conda info
          command: |
            conda info --envs
      - run:
          name: Activate conda env
          command: |
            conda init bash
            source ~/.bashrc
            conda activate << parameters.conda-environment-name >>
workflows:
  version: 2
  diagnostic-tool-deploy:
      jobs:
        - test:
            conda-environment-name: diagnostic-tool
